// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddJobListing(ctx context.Context, arg AddJobListingParams) error
	CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error)
	CreateCandidateApplication(ctx context.Context, arg CreateCandidateApplicationParams) (CandidateApplication, error)
	CreateCandidateSwipe(ctx context.Context, arg CreateCandidateSwipeParams) error
	CreateEmployer(ctx context.Context, arg CreateEmployerParams) (Employer, error)
	CreateEmployerApplication(ctx context.Context, arg CreateEmployerApplicationParams) (EmployerApplication, error)
	CreateEmployerSwipes(ctx context.Context, arg CreateEmployerSwipesParams) error
	CreatePastExperience(ctx context.Context, arg CreatePastExperienceParams) (PastExperience, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteCandidate(ctx context.Context, id int64) error
	DeleteCandidateApplication(ctx context.Context, arg DeleteCandidateApplicationParams) error
	DeleteCandidateSwipe(ctx context.Context, arg DeleteCandidateSwipeParams) error
	DeleteEmployer(ctx context.Context, id int64) error
	DeleteEmployerApplication(ctx context.Context, arg DeleteEmployerApplicationParams) error
	DeleteEmployerSwipe(ctx context.Context, arg DeleteEmployerSwipeParams) error
	DeletePastExperience(ctx context.Context, arg DeletePastExperienceParams) error
	GetCandidate(ctx context.Context, id int64) (Candidate, error)
	GetCandidateApplicationsByEmployer(ctx context.Context, employerID int64) ([]CandidateApplication, error)
	GetCandidateApplicationsByStatusAccepted(ctx context.Context, candidateID int64) ([]CandidateApplication, error)
	GetCandidateApplicationsByStatusPending(ctx context.Context, candidateID int64) ([]CandidateApplication, error)
	GetCandidateApplicationsByStatusRejected(ctx context.Context, candidateID int64) ([]CandidateApplication, error)
	GetCandidateApplicationsByStatusSubmitted(ctx context.Context, candidateID int64) ([]CandidateApplication, error)
	GetCandidateIDsByEmployer(ctx context.Context, employerID int64) ([]int64, error)
	GetCandidateIdByUsername(ctx context.Context, username string) (int64, error)
	GetCandidateSwipe(ctx context.Context, arg GetCandidateSwipeParams) ([]CandidateSwipe, error)
	GetEmployer(ctx context.Context, id int64) (Employer, error)
	GetEmployerApplicationsByCandidate(ctx context.Context, candidateID int64) ([]EmployerApplication, error)
	GetEmployerApplicationsByStatusAccepted(ctx context.Context, candidateID int64) ([]EmployerApplication, error)
	GetEmployerApplicationsByStatusPending(ctx context.Context, candidateID int64) ([]EmployerApplication, error)
	GetEmployerApplicationsByStatusRejected(ctx context.Context, candidateID int64) ([]EmployerApplication, error)
	GetEmployerApplicationsByStatusSubmitted(ctx context.Context, candidateID int64) ([]EmployerApplication, error)
	GetEmployerIdByUsername(ctx context.Context, username string) (int64, error)
	GetEmployerSwipe(ctx context.Context, arg GetEmployerSwipeParams) (EmployerSwipe, error)
	GetJobIDsByCandidate(ctx context.Context, candidateID int64) ([]string, error)
	GetPastExperience(ctx context.Context, id int64) (PastExperience, error)
	GetRejectedCandidateIdsByEmployer(ctx context.Context, employerID int64) ([]int64, error)
	GetRejectedJobIdsByCandidate(ctx context.Context, candidateID int64) ([]string, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]Candidate, error)
	ListEmployers(ctx context.Context, arg ListEmployersParams) ([]Employer, error)
	ListPastExperiences(ctx context.Context, arg ListPastExperiencesParams) ([]PastExperience, error)
	UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) (Candidate, error)
	UpdateCandidateApplication(ctx context.Context, arg UpdateCandidateApplicationParams) (CandidateApplication, error)
	UpdateCandidateApplicationStatus(ctx context.Context, arg UpdateCandidateApplicationStatusParams) error
	UpdateEmployer(ctx context.Context, arg UpdateEmployerParams) (Employer, error)
	UpdateEmployerApplication(ctx context.Context, arg UpdateEmployerApplicationParams) (EmployerApplication, error)
	UpdateEmployerApplicationStatus(ctx context.Context, arg UpdateEmployerApplicationStatusParams) error
	UpdatePastExperience(ctx context.Context, arg UpdatePastExperienceParams) (PastExperience, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
